version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: halyk_task
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --transaction-isolation=SERIALIZABLE
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: go_app1
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: "8080"
      DATABASE_URL: "app:password@tcp(db:3306)/halyk_task?parseTime=true"
    command: ["go", "run", "cmd/app/app.go"]
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app

  migrate:
    build: .
    container_name: go_migrate1
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "mysql://app:password@tcp(db:3306)/halyk_task?parseTime=true"
    command: ["go", "run", "cmd/migrate/migrate.go"]
    volumes:
      - .:/migrate
    working_dir: /migrate

volumes:
  mysql_data: